wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692765852.80731
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 1
      - 5
    viz:
      residuals:
        id: wandb/residuals_plot/v1
        historyFieldSettings:
          x-axis: _step
          key: residuals
